# Generated by Django 6.0.4 on 2026-04-24 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstory',
            options={'verbose_name_plural': 'User Stories'},
        ),
    ]
